# Minimal run without factors
csv: data/returns.csv
benchmark_csv: data/benchmark.csv
lookback: 126
step: 21
objective: max_return
cov_model: sample
refine_every: 1
seed: 3
skip_plot: true
out: runs/minimal
