{% set version = environ.get('PKG_VERSION', '0.4.0') %}

package:
  name: neuro-ant-optimizer
  version: {{ version }}

source:
  path: ..

build:
  noarch: false
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.23
    - torch >=2.0
    - scipy >=1.10
    - psutil >=5.9

about:
  home: https://github.com/quantresearch/neuro-ant-optimizer
  license: MIT
  summary: Neural-guided Ant Colony Portfolio Optimizer with robust constraints
  description: |
    Conda recipe for the neuro-ant-optimizer project. Installs the Python package and
    its runtime dependencies so the backtesting CLI and optimizer APIs are ready to use.

extra:
  recipe-maintainers:
    - quantresearch
