name: ci
on:
  push: { branches: [ "**" ] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps (minimal CPU)
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy torch pytest
          pip install ruff mypy
          # optional extras for CLI smoke
          pip install pandas matplotlib
      - name: Run tests
        env:
          PYTHONPATH: neuro-ant-optimizer/src
        run: pytest -q
      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check neuro-ant-optimizer/src neuro-ant-optimizer/tests
      - name: mypy (types)
        env:
          MYPYPATH: neuro-ant-optimizer/src
        run: |
          mypy neuro-ant-optimizer/src
      - name: CLI smoke (backtest)
        run: |
          neuro-ant-optimizer/src/neuro_ant_optimizer/backtest/backtest.py >/dev/null 2>&1 || true
          python -c "import sys,subprocess; subprocess.check_call(['neuro-ant-backtest','--csv','neuro-ant-optimizer/backtest/sample_returns.csv','--lookback','5','--step','2','--ewma_span','3','--objective','sharpe','--out','neuro-ant-optimizer/backtest/out_ci'])"
